# Generated by Django 5.2.5 on 2025-08-13 02:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=500)),
                ("solicitation_number", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("posted_date", models.DateTimeField()),
                ("response_date", models.DateTimeField(blank=True, null=True)),
                ("award_date", models.DateTimeField(blank=True, null=True)),
                ("source_url", models.URLField()),
                ("source_api", models.CharField(default="sam.gov", max_length=50)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.agency"
                    ),
                ),
                (
                    "naics_codes",
                    models.ManyToManyField(blank=True, to="core.naicscode"),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
                "indexes": [
                    models.Index(
                        fields=["solicitation_number"],
                        name="opportuniti_solicit_68571d_idx",
                    ),
                    models.Index(
                        fields=["posted_date"], name="opportuniti_posted__5c2dfd_idx"
                    ),
                    models.Index(
                        fields=["response_date"], name="opportuniti_respons_0e60e3_idx"
                    ),
                ],
            },
        ),
    ]
