# Generated by Django 5.2.5 on 2025-08-13 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("opportunities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="additional_info_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="ai_analysis_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="archive_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="archive_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="award_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="award_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="base_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="classification_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="compliance_checked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="documents_fetched",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="office_address",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="opportunity_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="place_of_performance",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="point_of_contact",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="raw_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Full API response data"
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="resource_links",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="set_aside_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.agency",
            ),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["opportunity_type"], name="opportuniti_opportu_a0cf41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["set_aside_type"], name="opportuniti_set_asi_a84e83_idx"
            ),
        ),
    ]
