# Generated by Django 5.2.5 on 2025-08-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunities", "0002_opportunity_additional_info_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="usaspending_analyzed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="usaspending_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="USASpending.gov analysis results"
            ),
        ),
    ]
