# Generated by Django 5.2.5 on 2025-08-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunities", "0003_add_usaspending_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="ai_analysis_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="AI-powered opportunity analysis"
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="compliance_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="AI compliance check results"
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="generated_content",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="AI-generated content (outlines, summaries)",
            ),
        ),
    ]
