# Generated by Django 5.2.5 on 2025-08-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_integration", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aitask",
            name="ai_service",
        ),
        migrations.AddField(
            model_name="aitask",
            name="ai_provider",
            field=models.CharField(
                choices=[
                    ("claude", "Claude (Anthropic)"),
                    ("gemini", "Google Gemini"),
                    ("openrouter", "OpenRouter"),
                ],
                default="claude",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="aitask",
            name="confidence_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aitask",
            name="model_used",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="aitask",
            name="processing_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aitask",
            name="tokens_used",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aitask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("analyze_opportunity", "Analyze Opportunity"),
                    ("compliance_check", "Compliance Check"),
                    ("generate_content", "Generate Content"),
                    ("summarize", "Summarize Document"),
                    ("draft", "Draft Content"),
                    ("quality", "Quality Review"),
                ],
                max_length=30,
            ),
        ),
    ]
