# Generated by Django 5.2.5 on 2025-08-14 00:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_integration", "0002_add_ai_tracking_fields"),
        ("opportunities", "0004_add_ai_analysis_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BidDecisionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("BID", "Bid"),
                            ("NO_BID", "No Bid"),
                            ("WATCH", "Watch"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "overall_score",
                    models.FloatField(help_text="Overall decision score (0-100)"),
                ),
                (
                    "confidence_score",
                    models.FloatField(help_text="AI confidence in analysis (0.0-1.0)"),
                ),
                ("strategic_alignment", models.FloatField()),
                ("capability_match", models.FloatField()),
                ("market_position", models.FloatField()),
                ("estimated_value", models.FloatField()),
                ("profit_potential", models.FloatField()),
                ("resource_requirements", models.FloatField()),
                ("technical_risk", models.FloatField()),
                ("schedule_risk", models.FloatField()),
                ("competitive_risk", models.FloatField()),
                ("rationale", models.TextField()),
                ("key_strengths", models.JSONField(default=list)),
                ("key_concerns", models.JSONField(default=list)),
                ("action_items", models.JSONField(default=list)),
                (
                    "estimated_bid_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "win_probability",
                    models.FloatField(
                        blank=True,
                        help_text="Estimated win probability (0.0-1.0)",
                        null=True,
                    ),
                ),
                ("decision_date", models.DateTimeField(auto_now_add=True)),
                ("reviewed", models.BooleanField(default=False)),
                ("review_date", models.DateTimeField(blank=True, null=True)),
                (
                    "actual_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BID", "Bid"),
                            ("NO_BID", "No Bid"),
                            ("WATCH", "Watch"),
                        ],
                        help_text="Final decision made",
                        max_length=10,
                    ),
                ),
                ("bid_submitted", models.BooleanField(default=False)),
                ("contract_awarded", models.BooleanField(default=False)),
                ("won_contract", models.BooleanField(default=False)),
                (
                    "actual_bid_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opportunity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bid_decision",
                        to="opportunities.opportunity",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-decision_date"],
                "indexes": [
                    models.Index(
                        fields=["recommendation"], name="ai_integrat_recomme_d45fa1_idx"
                    ),
                    models.Index(
                        fields=["overall_score"], name="ai_integrat_overall_a5e67b_idx"
                    ),
                    models.Index(
                        fields=["decision_date"], name="ai_integrat_decisio_fa3255_idx"
                    ),
                    models.Index(
                        fields=["win_probability"],
                        name="ai_integrat_win_pro_9d0725_idx",
                    ),
                ],
            },
        ),
    ]
