# Generated by Django 5.2.5 on 2025-08-14 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collaboration", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="proposalsection",
            name="content",
            field=models.TextField(
                blank=True, help_text="Rich text content of the section"
            ),
        ),
        migrations.AddField(
            model_name="proposalsection",
            name="last_modified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proposalsection",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_modified_sections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
