# Generated by Django 5.2.5 on 2025-08-14 01:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collaboration", "0002_proposalsection_content_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "section_types",
                    models.JSONField(
                        default=list, help_text="Section types this template applies to"
                    ),
                ),
                (
                    "required_reviews",
                    models.JSONField(default=list, help_text="Required review types"),
                ),
                (
                    "approval_sequence",
                    models.JSONField(
                        default=list, help_text="Ordered list of approval levels"
                    ),
                ),
                (
                    "auto_advance_conditions",
                    models.JSONField(
                        default=dict, help_text="Conditions for auto-advancing"
                    ),
                ),
                (
                    "default_review_duration",
                    models.IntegerField(
                        default=3, help_text="Default review duration in days"
                    ),
                ),
                (
                    "default_approval_duration",
                    models.IntegerField(
                        default=2, help_text="Default approval duration in days"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_templates",
                        to="collaboration.proposalteam",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SectionWorkflowInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_review", "In Review"),
                            ("in_approval", "In Approval"),
                            ("completed", "Completed"),
                            ("blocked", "Blocked"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("current_step", models.CharField(blank=True, max_length=50)),
                ("steps_completed", models.JSONField(default=list)),
                ("steps_pending", models.JSONField(default=list)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional workflow data"
                    ),
                ),
                (
                    "section",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow",
                        to="collaboration.proposalsection",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="collaboration.workflowtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SectionApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "approval_level",
                    models.CharField(
                        choices=[
                            ("technical_lead", "Technical Lead"),
                            ("proposal_manager", "Proposal Manager"),
                            ("team_lead", "Team Lead"),
                            ("quality_assurance", "Quality Assurance"),
                            ("compliance_officer", "Compliance Officer"),
                            ("final_authority", "Final Authority"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("conditional", "Conditionally Approved"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="Approver's comments or conditions"
                    ),
                ),
                (
                    "conditions",
                    models.TextField(
                        blank=True, help_text="Conditions that must be met"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "section_version",
                    models.TextField(help_text="Content hash or version identifier"),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="collaboration.proposalsection",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["section", "status"],
                        name="collaborati_section_7a612b_idx",
                    ),
                    models.Index(
                        fields=["approver", "status"],
                        name="collaborati_approve_fd56da_idx",
                    ),
                    models.Index(
                        fields=["approval_level"], name="collaborati_approva_118a98_idx"
                    ),
                    models.Index(
                        fields=["due_date"], name="collaborati_due_dat_abffd7_idx"
                    ),
                ],
                "unique_together": {("section", "approval_level")},
            },
        ),
        migrations.CreateModel(
            name="SectionReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("technical", "Technical Review"),
                            ("compliance", "Compliance Review"),
                            ("editorial", "Editorial Review"),
                            ("final", "Final Review"),
                            ("quality", "Quality Assurance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "instructions",
                    models.TextField(
                        blank=True, help_text="Specific review instructions"
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, help_text="Reviewer's feedback and comments"
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("approve", "Approve"),
                            ("approve_with_changes", "Approve with Minor Changes"),
                            ("reject", "Reject - Major Revision Needed"),
                            ("incomplete", "Incomplete Review"),
                        ],
                        max_length=20,
                    ),
                ),
                ("technical_accuracy", models.IntegerField(blank=True, null=True)),
                ("clarity_score", models.IntegerField(blank=True, null=True)),
                ("compliance_score", models.IntegerField(blank=True, null=True)),
                ("overall_quality", models.IntegerField(blank=True, null=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_reviews_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="collaboration.proposalsection",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["section", "status"],
                        name="collaborati_section_36cd6e_idx",
                    ),
                    models.Index(
                        fields=["reviewer", "status"],
                        name="collaborati_reviewe_3e5047_idx",
                    ),
                    models.Index(
                        fields=["due_date"], name="collaborati_due_dat_e1e987_idx"
                    ),
                ],
                "unique_together": {("section", "reviewer", "review_type")},
            },
        ),
        migrations.AddIndex(
            model_name="workflowtemplate",
            index=models.Index(
                fields=["team", "is_active"], name="collaborati_team_id_f1040a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sectionworkflowinstance",
            index=models.Index(fields=["status"], name="collaborati_status_e81935_idx"),
        ),
        migrations.AddIndex(
            model_name="sectionworkflowinstance",
            index=models.Index(
                fields=["current_step"], name="collaborati_current_9684a3_idx"
            ),
        ),
    ]
