# Generated by Django 5.2.5 on 2025-08-13 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
        ("opportunities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="compliance_notes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="document",
            name="contains_requirements",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="document",
            name="document_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="document",
            name="is_pws",
            field=models.BooleanField(
                default=False, help_text="Is this a Performance Work Statement?"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="is_sow",
            field=models.BooleanField(
                default=False, help_text="Is this a Statement of Work?"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="key_requirements",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="document",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="processing_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="document",
            name="source_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="document",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_path",
            field=models.FileField(blank=True, null=True, upload_to="documents/%Y/%m/"),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_size",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="document",
            name="opportunity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="opportunities.opportunity",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["opportunity", "processing_status"],
                name="documents_d_opportu_3ec29e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["document_type"], name="documents_d_documen_40c475_idx"
            ),
        ),
    ]
