# Generated by Django 5.2.5 on 2025-08-14 02:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collaboration", "0003_workflowtemplate_sectionworkflowinstance_and_more"),
        ("documents", "0002_document_compliance_notes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssemblyConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("include_cover_page", models.BooleanField(default=True)),
                ("include_table_of_contents", models.BooleanField(default=True)),
                ("include_executive_summary", models.BooleanField(default=True)),
                ("include_appendices", models.BooleanField(default=True)),
                (
                    "page_size",
                    models.CharField(
                        choices=[
                            ("letter", 'Letter (8.5" x 11")'),
                            ("a4", "A4"),
                            ("legal", 'Legal (8.5" x 14")'),
                        ],
                        default="letter",
                        max_length=10,
                    ),
                ),
                (
                    "font_family",
                    models.CharField(default="Times New Roman", max_length=50),
                ),
                ("font_size", models.PositiveIntegerField(default=12)),
                (
                    "line_spacing",
                    models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
                ),
                (
                    "margin_top",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
                ),
                (
                    "margin_bottom",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
                ),
                (
                    "margin_left",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
                ),
                (
                    "margin_right",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assembly_configs",
                        to="collaboration.proposalteam",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField()),
                (
                    "include_in_toc",
                    models.BooleanField(
                        default=True, help_text="Include in table of contents"
                    ),
                ),
                (
                    "page_break_before",
                    models.BooleanField(
                        default=False, help_text="Insert page break before section"
                    ),
                ),
                (
                    "page_break_after",
                    models.BooleanField(
                        default=False, help_text="Insert page break after section"
                    ),
                ),
                (
                    "custom_title",
                    models.CharField(
                        blank=True, help_text="Override section title", max_length=255
                    ),
                ),
                (
                    "custom_numbering",
                    models.CharField(
                        blank=True, help_text="Custom section numbering", max_length=50
                    ),
                ),
                (
                    "assembly_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_sections",
                        to="documents.assemblyconfiguration",
                    ),
                ),
                (
                    "proposal_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_mappings",
                        to="collaboration.proposalsection",
                    ),
                ),
            ],
            options={
                "ordering": ["assembly_config", "order"],
            },
        ),
        migrations.AddField(
            model_name="assemblyconfiguration",
            name="sections",
            field=models.ManyToManyField(
                through="documents.DocumentSection", to="collaboration.proposalsection"
            ),
        ),
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("proposal", "Proposal Template"),
                            ("section", "Section Template"),
                            ("cover_page", "Cover Page Template"),
                            ("appendix", "Appendix Template"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "content_template",
                    models.TextField(help_text="HTML template with variables"),
                ),
                (
                    "variables",
                    models.JSONField(
                        default=dict, help_text="Available template variables"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Default template for organization"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_templates",
                        to="collaboration.proposalteam",
                    ),
                ),
            ],
            options={
                "ordering": ["template_type", "name"],
            },
        ),
        migrations.AddField(
            model_name="assemblyconfiguration",
            name="base_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assembly_configs",
                to="documents.documenttemplate",
            ),
        ),
        migrations.CreateModel(
            name="DocumentVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Variable name (e.g., 'company_name')", max_length=100
                    ),
                ),
                (
                    "display_name",
                    models.CharField(help_text="Human-readable name", max_length=255),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "variable_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("boolean", "Boolean"),
                            ("list", "List"),
                            ("calculated", "Calculated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("default_value", models.TextField(blank=True)),
                ("current_value", models.TextField(blank=True)),
                ("is_required", models.BooleanField(default=False)),
                (
                    "calculation_formula",
                    models.TextField(
                        blank=True,
                        help_text="Python expression for calculated variables",
                    ),
                ),
                (
                    "assembly_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="documents.assemblyconfiguration",
                    ),
                ),
            ],
            options={
                "ordering": ["assembly_config", "name"],
            },
        ),
        migrations.CreateModel(
            name="ExportFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "format_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("docx", "Microsoft Word"),
                            ("html", "HTML"),
                            ("txt", "Plain Text"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "settings",
                    models.JSONField(
                        default=dict, help_text="Format-specific configuration"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("requires_external_service", models.BooleanField(default=False)),
                ("external_service_config", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["format_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["format_type", "is_active"],
                        name="documents_e_format__c719d1_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress_percentage", models.PositiveIntegerField(default=0)),
                (
                    "output_file",
                    models.FileField(blank=True, null=True, upload_to="exports/%Y/%m/"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "job_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique job identifier",
                        unique=True,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict, help_text="Export parameters and options"
                    ),
                ),
                (
                    "assembly_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_jobs",
                        to="documents.assemblyconfiguration",
                    ),
                ),
                (
                    "export_format",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_jobs",
                        to="documents.exportformat",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="documentsection",
            index=models.Index(
                fields=["assembly_config", "order"],
                name="documents_d_assembl_b91030_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentsection",
            unique_together={("assembly_config", "proposal_section")},
        ),
        migrations.AddIndex(
            model_name="documenttemplate",
            index=models.Index(
                fields=["template_type", "is_active"],
                name="documents_d_templat_e7a2c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documenttemplate",
            index=models.Index(
                fields=["team", "is_default"], name="documents_d_team_id_144d19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assemblyconfiguration",
            index=models.Index(
                fields=["team", "is_default"], name="documents_a_team_id_99c4be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentvariable",
            index=models.Index(
                fields=["assembly_config", "variable_type"],
                name="documents_d_assembl_cd8036_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentvariable",
            unique_together={("assembly_config", "name")},
        ),
        migrations.AddIndex(
            model_name="exportjob",
            index=models.Index(
                fields=["assembly_config", "status"],
                name="documents_e_assembl_0a9cd8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="exportjob",
            index=models.Index(
                fields=["requested_by", "status"], name="documents_e_request_e77001_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exportjob",
            index=models.Index(fields=["job_id"], name="documents_e_job_id_09ac31_idx"),
        ),
    ]
