# Generated by Django 5.2.5 on 2025-08-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="action_url",
            field=models.URLField(
                blank=True,
                help_text="URL to navigate to when notification is clicked",
                null=True,
            ),
        ),
    ]
