# Generated by Django 5.2.5 on 2025-08-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_alter_notification_action_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="action_label",
            field=models.CharField(
                blank=True,
                help_text="Label for the action button",
                max_length=50,
                null=True,
            ),
        ),
    ]
